services:
  - type: web
    name: piston-api
    env: docker
    repo: https://github.com/Divyesh-Chauhan/piston
    branch: main
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "docker-compose up"
    autoDeploy: true
